project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static


from app import views 


urlpatterns = [
    # Examples:
    # url(r'^$', 'project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),


    # form view
    url(r'^city_create/', 'app.views.edit_city', name="create_city"),  
    url(r'^city_edit/(?P<pk>\d+)', 'app.views.edit_city', name="edit_city"),  
    url(r'^city_search/', 'app.views.city_search'),  
    url(r'^city_search_post/', 'app.views.city_search_post'), 
    # class based view 
    url(r'^statecapital_detail_class_view/(?P<pk>\d+)/', views.StatecapitalDetailView.as_view() ),
    url(r'^city_list_class_view/', views.StatecapitalListView.as_view() ),

    url(r'^city_detail_class_view/(?P<pk>\d+)/', views.CityDetailView.as_view() ),
    url(r'^city_list_class_view/', views.CityListView.as_view() ),

    url(r'^state_detail_class_view/(?P<pk>\d+)/', views.StateDetailView.as_view() ),
    url(r'^state_list_class_view/', views.StateListView.as_view() ),


    # new view 
    url(r'^statecapital_list/', 'app.views.statecapital_list'),
    url(r'^statecapital_detail/(?P<pk>\d+)/', 'app.views.statecapital_detail'),

    url(r'^city_list/', 'app.views.city_list'),
    url(r'^city_detail/(?P<pk>\d+)/', 'app.views.city_detail'),

    url(r'^state_list/', 'app.views.state_list'),
    url(r'^state_detail/(?P<pk>\d+)/', 'app.views.state_detail'),


    ## all the old views 
    url(r'^admin/', include(admin.site.urls)),

    # url(r'^state_list/(?P<letter>\w+)/(?P<sort>\w+)/', "app.views.state_list"),
    # url(r'^city_list/(?P<letter>\w+)/(?P<sort>\w+)/', "app.views.city_list"),


    url(r'^first_view/(?P<starts_with>\w+)/$', 'app.views.first_view'),
    url(r'^form_view/', 'app.views.form_view'),
    # url(r'^class_pased_view/', GetPots.as_view()),
    url(r'^template_view/','app.views.template_view'),
    url(r'^template_view2/','app.views.template_view2'),
    url(r'^get_post/', 'app.views.get_post'),  
    url(r'^list/', 'app.views.list'),
    url(r'^detail/(?P<pk>\d+)/', 'app.views.detail'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models

# Create your models here.

class State(models.Model):
	abbreviation = models.CharField(max_length=2, null=True, blank=True)
	name = models.CharField(max_length=100, null=True, blank=True)

	def __unicode__(self):
		return '%s' % self.name


class StateCapital(models.Model):
	state = models.OneToOneField("app.State", null=True)
	name = models.CharField(max_length=100, null=True, blank=True)
	latitude = models.FloatField(null=True, blank=True)
	longitude = models.FloatField(null=True, blank=True)
	population = models.IntegerField(null=True, blank=True)

	def __unicode__(self):
		return '%s' % self.name

class City(models.Model):
	state = models.ForeignKey("app.State", null= True)
	name = models.CharField(max_length=100, null= True, blank=True)
	county = models.CharField(max_length=100, null=True,blank=True)
	latitude = models.FloatField(null= True, blank = True)
	longitude = models.FloatField(null=True,blank = True)
	zipcode = models.CharField(max_length=100, null= True, blank=True)


	def __unicode__(self):
		return '%s' % self.name

app/templates/base.html
<!-- t0 wrap my html file and css, js files -->
<!-- t0 check that we need to insect and check the concle  -->


{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Business Casual - Start Bootstrap Theme</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/business-casual.css' %}" rel="stylesheet">

    <!-- Fonts -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div class="brand">Satate Project</div>
    <div class="address-bar">CODED STATE PROJECT</div>

    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">

            
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                <a class="navbar-brand" href="index.html">Business Casual</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="/state_list/">Sates</a>
                    </li>
                    <li>
                        <a href="/city_list/">Cities</a>
                    </li>
                    <li>
                        <a href="/statecapital_list/">Capitails</a>
                    </li>
                    <li>
                        <a href="/city_search/">City Search</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>

        <!-- /.container -->
    </nav>

	{%block content %}
	{% endblock %}

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- Script to Activate the Carousel -->
    <script>
    $('.carousel').carousel({
        interval: 5000 //changes the speed
    })
    </script>

</body>

</html>

app/templates/base2.html
<!DOCTYPE html>
<<!DOCTYPE html>
<html>
<head>
	<title>I am a grumpy cat</title>
</head>
	<body bgcolor="#000000" >
	<font color="white">
		<p style="font-family:courier">
			{% for state, cities in states.items %}

				<h3>{{ state }} </h3> </br>

				{% for city in cities %}
					{{ city }} <br>
				{% endfor %}


			{% endfor %}
		</p>
	</font>
	</body>
</html>

app/templates/city_detail.html
{%extends 'base.html' %}
{% load staticfiles %}

<body>

    {%block content %}
    <div class="container">

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">
                        City: <strong>{{ city.name }}</strong>
                    </h2>
                    <hr>
                </div>
                <div class="col-md-8">
                    <!-- Embedded Google Map using an iframe - to select your location find it on Google maps and paste the link as the iframe src. If you want to use the Google Maps API instead then have at it! -->
                    <iframe width="100%" height="400" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?hl=en&amp;ie=UTF8&amp;ll={{ city.latitude }}, {{ city.longitude }}&amp;spn=56.506174,79.013672&amp;t=m&amp;z=7&amp;output=embed"></iframe>
                </div>
                <div class="col-md-4">
                    <p>City county:
                        <strong>{{ city.county }}</strong>
                    </p>
                    <p>City Zipcode :
                        <strong>{{ city.zipcode }} </strong>
                    </p>
                    <p>State :
                        <strong>{{ city.state.name }} </strong>
                    </p>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>


    </div>
    {%endblock%}
    <!-- /.container -->

app/templates/city_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container">

        <div class="row" style="background-color: #FFF;">
            <div class="box">

	            <div class="col-xs-2 col-md-2"></div>
				<div class="col-xs-8 col-md-8">

				{{ crispy form }}
							<br>
							<br>
{# 
							<p style="margin-top:35px;">
							{% for city in cities %}
								{{ city.name }}
								{{ city.zipcode }}
								<br>
							{% endfor %}
							</p> #}
				</div>
				<div class="col-xs-2 col-md-2"></div>
            </div>
        </div>

{% endblock %}

app/templates/city_list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    <div class="container">

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <p class='city-block'>
                        {% for state in states %}
                            {{ state.name}}
                        {% endfor %}
                    </p>
                </div>
            </div>
        </div>

        {% for city in cities %}
            <div class="row">
                <div class="box">
                    <div class="col-lg-12">
                    <h2 class ="intro-text text-center">
                        <a href="/city_detail/{{ city.pk }}/"> 
                            {{ city.name }} 
                        </a>
                    </h2>
                    <hr>
                    <p class='city-box'>
                        <b> County: </b>{{ city.county }} | <b>State:</b>{{ city.state}} |
                        <b> Zipcode: </b> {{ city.zipcode }} 
                    </p>
                </div>
            </div>
        </div>
        {%endfor%}
    </div>
{%endblock%}

app/templates/city_search.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container">

        <div class="row" style="background-color: #FFF;">
            <div class="box">

	            <div class="col-xs-4 col-md-4"></div>
				<div class="col-xs-4 col-md-4">

						{% crispy form %}
							{% for city in cities %}
								{{ city.name }}
								{{ city.zipcode }}
								<br>
							{% endfor %}


				</div>
				<div class="col-xs-4 col-md-4"></div>
            </div>
        </div>

{% endblock %}

app/templates/city_search_post.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Search with post</title>
</head>
<body>
	<form action="/city_search_post/" method="POST">
		{% csrf_token %}

		City: 
		
		{{ form.city }}
		<br>

		State: 
		{{ form.state }} 
		<br>
		<input type="submit" value="Search">

	</form>
{{ form.errors }}
{% for city in cities %}
	{{ city.name }} | {{ city.zipcode }}
	<br>
{% endfor %}

</body>
</html>

app/templates/create_city.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container">

        <div class="row" style="background-color: #FFF;">
            <div class="box">

	            <div class="col-xs-4 col-md-4"></div>
				<div class="col-xs-4 col-md-4">

						{% crispy form %}
							hi there 


				</div>
				<div class="col-xs-4 col-md-4"></div>
            </div>
        </div>

{% endblock %}

app/templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Detail </title>
</head>
<body>

	State Object: {{ state }}
	<h3> State Name: {{state.name }} </h3>
	<b> State Capital:</b>  {{ state.statecapital.name }} <br>
	<b> State Capital Population: </b> {{ state.statecapital.population }} <br>
	
</body>
</html>

app/templates/list.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>List view</title>
</head>
<body>

	<p>Query Set: {{ states }} </p>
	<br>


	{% for state in states %}
		<a href="/detail/{{ state.pk }}/"> {{ state.name}} </a>

		<br>
	{% endfor %}

</body>
</html>

app/templates/state_detail.html
{%extends 'base.html' %}
{% load staticfiles %}

<body>

    {%block content %}
    <div class="container">

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">State: 
                        <strong>{{ state.name }}</strong>
                    </h2>
                    <hr>
                </div>
                <div class="col-md-8">
                    <!-- Embedded Google Map using an iframe - to select your location find it on Google maps and paste the link as the iframe src. If you want to use the Google Maps API instead then have at it! -->
                    <iframe width="100%" height="400" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?hl=en&amp;ie=UTF8&amp;ll={{ state.statecapital.latitude }}, {{ state.statecapital.longitude }}&amp;spn=56.506174,79.013672&amp;t=m&amp;z=7&amp;output=embed"></iframe>
                </div>
                <div class="col-md-4">
                    <p>State Capital:
                        <strong>{{ state.statecapital.name }}</strong>
                    </p>
                    <p>State Capital Population :
                        <strong>{{ state.statecapital.population }} </strong>
                    </p>
                    <p> Cities: </p>
                        <strong>   
                            <ul>        
                            {% for city in state.city_set.all|slice:":20" %}
                                    <li>{{ city.name}} </li>
                            {% endfor %}
                            </ul>
                        </strong>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>


    </div>
    {%endblock%}
    <!-- /.container -->

app/templates/state_list.html
<!-- t0 wrap my html file and css, js files -->
<!-- t0 check that we need to insect and check the concle  -->

{% extends 'base.html' %}
{% load staticfiles %}

    {% block content %}
    <div class="container">
        {% for state in states %}
        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>   
                    <h2 class ="intro-text text-center">
                        <a href="/state_detail/{{ state.pk }}/"> {{ state.name }} </a>
                    </h2>
                    <hr>
                    <p class='city-box'>
                        {% for city in state.city_set.all|slice:':30' %}
                            {{ city.name }} 

                            {% if forloop.last %}
                                &nbsp
                            {% else %}
                                |
                            {% endif %}
                        {% endfor %}

                    </p>
                </div>
            </div>
        </div>
        {%endfor%}

    </div>
    {%endblock%}

app/templates/statecapital_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load humanize %}
<body>

    {%block content %}
    <div class="container">

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Statecapital: 
                        <strong>{{ statecapital.name }}</strong>
                    </h2>
                    <hr>
                </div>
                <div class="col-md-8">
                    <!-- Embedded Google Map using an iframe - to select your location find it on Google maps and paste the link as the iframe src. If you want to use the Google Maps API instead then have at it! -->
                    <iframe width="100%" height="400" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?hl=en&amp;ie=UTF8&amp;ll={{ statecapital.latitude }}, {{ statecapital.longitude }}&amp;spn=56.506174,79.013672&amp;t=m&amp;z=7&amp;output=embed"></iframe>
                </div>
                <div class="col-md-4">
                    <p class='city-box'>
                        <b> State: </b> {{ statecapital.state }} |
                        <b> Population: </b> {{ statecapital.population|intcomma }} 
                    </p>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>


    </div>
    {%endblock%}
    <!-- /.container -->

app/templates/statecapital_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load humanize %}

    {% block content %}
    <div class="container">
        {% for statecapital in statecapitals %}
        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>   
                    <h2 class ="intro-text text-center">
                        <a href="/statecapital_detail/{{ statecapital.pk }}/"> {{ statecapital.name }} </a>
                    </h2>
                    <hr>
                    <p class='city-box'>
                        <b> State: </b> {{ statecapital.state }} |
                        <b> Population: </b> {{ statecapital.population|intcomma }} 
                    </p>
                </div>
            </div>
        </div>
        {%endfor%}

    </div>
    {%endblock%}